### ISSUE TITLE
Theme requests

### ISSUE THREAD

**Issue by help-14** [help-14/magma#12]
If you have an idea for a theme and don't know how to code, make a picture mockup and post it here, someone will help you (maybe) :)

**Comment by lissy93** [comment]
Just came here to say, really nice dashboard :)
9Mb compressed container size is impressive. I wish I'd used Go in [mine](https://github.com/Lissy93/dashy), as Node.js, even just for the HTTP server is heavy AF.
Awesome work, keep it up!
P.s. Mind if I link to it [here](https://github.com/Lissy93/dashy#alternatives-)?

**Comment by help-14** [comment]
> Just came here to say, really nice dashboard :) 9Mb compressed container size is impressive. I wish I'd used Go in [mine](https://github.com/Lissy93/dashy), as Node.js, even just for the HTTP server is heavy AF. Awesome work, keep it up! P.s. Mind if I link to it [here](https://github.com/Lissy93/dashy#alternatives-)?

Sure thing :))) I use Deno for the first version, 20mb still quite lightweight but then I find out Deno don't support ARM so I moved to Go, I think it was a correct choice :)))
